version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "8000:8000"
    env_file:
    - ./.env.example
    depends_on:
      - db
    command: >
      bash -c "export DB_HOST=db && export DB_PORT=3306 && sleep 15 && php artisan migrate --seed && php artisan serve"
  db:
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_DATABASE: tasks
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - ./mysqldata:/var/lib/mysql

